### ISSUE TITLE
Missing values for  nested objects

### ISSUE THREAD

**Issue by oreshkor** [ant8e/sbt-i18n#5]
Hi, I've probably met some bug in the lib. On configuration like this:
en = {
  msg1.sub1 = a text
  msg4.sub2 = a text
  msg2 ="a parametrized text {0}"
  msg3 = "a text"
}
ru = {
  msg1.sub1 = ru text
  msg4.sub1 = какой-то текст
  msg4.sub2 = какой-то текст2
  msg2 ="un texte paramétré {0}"
  msg3 ="ru text"
}

It generates the following bundle object with missing """??? ru.msg1.sub1 ???""", """??? ru.msg4.sub2 ???""" values:

package org.example.i18n

object Bundle {
 abstract class I18N {
abstract class Msg1 {
def sub1: String
}

def msg1: Msg1

def msg2(x0: String): String
def msg3: String
abstract class Msg4 {
def sub1: String
def sub2: String
}

def msg4: Msg4

}
 object ru extends I18N {
object msg1 extends  Msg1 {
val sub1= """??? ru.msg1.sub1 ???"""
}

def msg2(x0: String): String= java.text.MessageFormat.format("""un texte paramétré {0}""", x0)
val msg3= """ru text"""
object msg4 extends  Msg4 {
val sub1= """какой-то текст"""
val sub2= """??? ru.msg4.sub2 ???"""
}

}
object en extends I18N {
object msg1 extends  Msg1 {
val sub1= """a text"""
}

def msg2(x0: String): String= java.text.MessageFormat.format("""a parametrized text {0}""", x0)
val msg3= """a text"""
object msg4 extends  Msg4 {
val sub1= """??? en.msg4.sub1 ???"""
val sub2= """a text"""
}

}
}

**Comment by ant8e** [comment]
Seems like a bug indeed! Thanks for the report. Will look into it
